# Generated by Django 4.1.5 on 2023-01-17 12:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('surname', models.CharField(max_length=35, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('age', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(90)])),
                ('course', models.CharField(max_length=100, null=True)),
                ('course_format', models.CharField(max_length=100, null=True)),
                ('course_type', models.CharField(max_length=100, null=True)),
                ('sum', models.IntegerField(null=True)),
                ('alreadyPaid', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utm', models.CharField(max_length=100, null=True)),
                ('msg', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(null=True)),
                ('group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.groupmodel')),
                ('manager', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='orders.ordermodel')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
