# Generated by Django 4.1.5 on 2023-01-17 19:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
        ('orders', '0004_alter_ordermodel_course_alter_ordermodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='alreadyPaid',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(-2147483647), django.core.validators.MaxLengthValidator(2147483647)]),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='course',
            field=models.CharField(choices=[('FS', 'FS'), ('QACX', 'QACX'), ('JCX', 'JCX'), ('JSCX', 'JSCX'), ('FE', 'FE'), ('PCX', 'PCX')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='course_format',
            field=models.CharField(choices=[('static', 'static'), ('online', 'online ')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='course_type',
            field=models.CharField(choices=[('pro', 'pro'), ('minimal', 'minimal'), ('premium', 'premium'), ('incubator', 'incubator'), ('vip', 'vip')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='groups.groupmodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='msg',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='sum',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(-2147483647), django.core.validators.MaxLengthValidator(2147483647)]),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='utm',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
