# Generated by Django 4.1.5 on 2023-01-17 19:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('orders', '0005_alter_ordermodel_alreadypaid_alter_ordermodel_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='alreadyPaid',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxLengthValidator(2147483647)]),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.groupmodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='sum',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxLengthValidator(2147483647)]),
        ),
    ]
