# Generated by Django 4.1.5 on 2023-01-17 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('orders', '0006_alter_ordermodel_alreadypaid_alter_ordermodel_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='groups.groupmodel'),
        ),
    ]
