# Generated by Django 4.1.5 on 2023-01-18 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('orders', '0007_alter_ordermodel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.groupmodel'),
        ),
    ]
