# Generated by Django 4.1.5 on 2023-01-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_ordermodel_options_alter_ordermodel_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='course',
            field=models.CharField(choices=[('FS', 'Fs'), ('QACX', 'Qacx'), ('JCX', 'Jcx'), ('JSCX', 'Jscx'), ('FE', 'Fe'), ('PCX', 'Pcx')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='course_format',
            field=models.CharField(choices=[('static', 'Static'), ('online', 'Online')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='course_type',
            field=models.CharField(choices=[('pro', 'Pro'), ('minimal', 'Minimal'), ('premium', 'Premium'), ('incubator', 'Incubator'), ('vip', 'Vip')], max_length=100, null=True),
        ),
    ]
