# Generated by Django 4.1.5 on 2023-01-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_ordermodel_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('В работе', 'In Work'), ('Новый', 'New'), ('Согласен', 'Agree'), ('Не согласен', 'Disagree'), ('Дубляж', 'Dubbling')], max_length=15, null=True),
        ),
    ]
