# Generated by Django 4.1.5 on 2023-02-02 22:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='alreadyPaid',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2147483647)]),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='msg',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='sum',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2147483647)]),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='utm',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
