# Generated by Django 4.1.5 on 2023-02-10 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_commentmodel_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='name',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-ЯїЇёЁ]*$', 'enter only alphanumeric characters')]),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='surname',
            field=models.CharField(max_length=35, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-ЯїЇёЁ]*$', 'enter only alphanumeric characters')]),
        ),
    ]
