# Generated by Django 4.1.5 on 2023-02-10 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_ordermodel_name_alter_ordermodel_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='name',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[a-zа-яёі]+$', 'enter only alphanumeric characters', flags='iu')]),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='surname',
            field=models.CharField(max_length=35, null=True, validators=[django.core.validators.RegexValidator('^[a-zа-яёі]+$', 'enter only alphanumeric characters')]),
        ),
    ]
