# Generated by Django 4.1.5 on 2023-02-10 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_ordermodel_name_alter_ordermodel_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='name',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[a-zа-яёі]+$', 'enter only alphanumeric characters', code='iu')]),
        ),
    ]
