# Generated by Django 4.1.5 on 2023-02-10 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_ordermodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='surname',
            field=models.CharField(max_length=35, null=True, validators=[django.core.validators.RegexValidator('^[a-zа-яёі]+$', 'enter only alphanumeric characters', code='iu')]),
        ),
    ]
