# Generated by Django 4.1.5 on 2023-02-12 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profilemodel_name_alter_profilemodel_surname'),
        ('orders', '0020_alter_ordermodel_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='manager',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.profilemodel'),
            preserve_default=False,
        ),
    ]
