# Generated by Django 4.1.5 on 2023-02-12 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_commentmodel_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ['-created_at']},
        ),
    ]
