# Generated by Django 4.1.5 on 2023-01-17 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(128)])),
            ],
            options={
                'db_table': 'groups',
            },
        ),
    ]
