# Generated by Django 4.1.5 on 2023-01-18 12:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-ЯїЇ]*$', 'enter only alphanumeric characters')])),
                ('surname', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-ЯїЇ]*$', 'enter only alphanumeric characters')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
