# Generated by Django 4.1.5 on 2023-02-12 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profilemodel_name_alter_profilemodel_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(blank=True, max_length=128, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(128), django.core.validators.RegexValidator('\\d', 'must contain 1 number (0-9)'), django.core.validators.RegexValidator('[^a-zA-Z\\d\\s:]', 'must contain 1 non-alpha numeric'), django.core.validators.RegexValidator('\\s', 'must not contain white spaces', inverse_match=True), django.core.validators.RegexValidator('[A-ZА-ЯЇ]', 'must contain 1 uppercase letter'), django.core.validators.RegexValidator('[a-zа-яї]', 'must contain 1 lowercase letter')]),
        ),
    ]
