# Generated by Django 4.1.5 on 2023-02-13 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_usermodel_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['-create_at']},
        ),
    ]
